### PR TITLE
Release

### PR DESCRIPTION
**Pull request by T4rk1n**
Add changelog and improve npmignore/setup.py in preparation for release.

@bpostlethwaite Please review

### CODE REVIEW

**Comment by alexcjohnson** [comment]
Heh our conversation mostly consisted of the questions above, ie wondering what we're really trying to accomplish with this repo - I could take my best guess but would guess someone involved in its creation could give a more informed statement.

**Comment by bpostlethwaite** [comment]
Right, dcc is meant for core dashboard widgets. It will grow slowly. However, over time we will accumulate all sorts of extra widgets and this will be their home. `dec` components will be supported and maintained. Often they will have been sponsored by a commercial entity.

**Comment by chriddyp** [comment]
Maybe something along the lines of:

> Dash Extra Components is a loose collection of Dash components written by engineers at Plotly. Some components are written for one-off projects and other components were [commercially sponsored by our customers](https://plot.ly/products/consulting-and-oem/).
> Components in Dash Extra Components weren't considered to be as "essential" to Dash as those contained in Dash Core Components. As such, these components won't necessarily have the same level of documentation or upkeep.

Alternatively worded.
> **Why Dash Extra Components?**
> Dash Core Components is our "essential" component suite for Dash. Not all components make the cut!
> Dash Extra Components is a looser, not-as-essential collection of components by Plotly. Some components were written for our own projects (`dec.TableOfContents` was written for the [Dash User Guide](https://dash.plot.ly)) while others were written for our [Dash Deployment Server](http://plot.ly/dash/pricing/) customers (e.g. `dec.Typehead`).
> Instead of creating a separate repository for each component, we decided to package up the components as a new package to ease discoverability and maintenance.
> Dash Extra Components are maintained by plotly. However, we don't view them quite as essential as our other Dash packages and, as such, won't be giving them as much attention with respect to upkeep and documentation. What you see is what you get!

**Comment by alexcjohnson** [comment]
Thanks @chriddyp, that's great - I'll include a version of your second one.

**Pull request merged**
